### ISSUE TITLE
Klayout feol failed with 5 DRC violations

### ISSUE THREAD

**Issue by hugodiasg** [hugodiasg/tt09-temp-sensor-clock_divider#1]
KLayout FEOL
Klayout feol failed with 2 DRC violations
Traceback (most recent call last):
File "/home/runner/work/tt08-square1/tt08-square1/tt/precheck/precheck.py", line 206, in main
check()
File "/home/runner/work/tt08-square1/tt08-square1/tt/precheck/precheck.py", line 179, in <lambda>
["KLayout FEOL", lambda: klayout_drc(args.gds, "feol")],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/tt08-square1/tt08-square1/tt/precheck/precheck.py", line 84, in klayout_drc
raise PrecheckFailure(
precheck_failure.PrecheckFailure: Klayout feol failed with 2 DRC violations

**Comment by hugodiasg** [comment]
magic &

In the tkcon:
load clock_divider
gds readonly true
gds read clock_divider.gds
save
save all modifications that pop up

In the tt_um_... .mag:
Cell -> Place Instance -> place clock_divider.mag

Other option is to run the tkcon commands directly in the tt_um_... .mag.
